### ISSUE TITLE
UPS Tracking number not found

### ISSUE THREAD

**Issue by razzam21** [ljmerza/ha-email-sensor#12]
The email and package tracking is working great.  I put a rule in my Gmail account that moves all of the emails that container tracking number into a folder and then point the email component at that folder.

I have a UPS email that the script doesn't seem to find the tracking number.  The code where you check for the tracking number on line 28.
`match = re.search('tracknum=(.*?)&AgreeToTermsAndConditions', link)`
I looked at the source code to the email in my folder that isn't matching I discovered that there are two additional patterns that you could match on.

Sample 1:
tracknum=ABCDEFGHIJKLMNOPQRST&type=

Sample 2:
tracknum=ABCDEFGHIJKLMNOPQRST&amp;AgreeToTermsAndConditions

I hope this helps.  Let me know if there is anything else I can do to help.

**Comment by ljmerza** [comment]
The sample 2 is the same as the current regex but you said there are 2 additional patterns?

**Comment by razzam21** [comment]
The second sample is the "&" is displayed as "&amp;" instead which is why I
think the script shows the email but didn't find the package number.

**Comment by ljmerza** [comment]
Ah ok, well the new pattern should work for all three

**Comment by razzam21** [comment]
Thank you
