### ISSUE TITLE
Allow name in config

### ISSUE THREAD

**Issue by arsaboo** [ljmerza/ha-email-sensor#13]
I share my config on Github for others to follow and would not like to publicize my email. It would be nice to be able to use `name` in the config with the default being how it is currently handled.

**Comment by ljmerza** [comment]
not sure what you mean, are you talking about the sensor name itself and hacing to use that for the tracking number card?

**Comment by arsaboo** [comment]
Apologies for the delayed reply. Yes, it will be nice to have the sensor name configurable.

**Comment by ljmerza** [comment]
Added
