### ISSUE TITLE
 IMAPClient update error: command: FETCH => [OVERQUOTA] Account exceeded command or bandwidth limits.

### ISSUE THREAD

**Issue by mmartoccia** [ljmerza/ha-email-sensor#16]
I am unable to use the mail sensor as I continually receive an 'OVERQUOTA' message on the fetch. Is there something I can do on my end to change this?

**Comment by ljmerza** [comment]
I assume you are using google api? check your develop console for quotas

**Comment by mmartoccia** [comment]
Are there API related calls for GMail in this app or is it simply using IMAP to fetch mail? I checked the API - I dont have it enabled.  Even if I did, I'm unsure how the current implementation would authenticate.  I do have a sizable inbox, is it possible that this could be the cause?

**Comment by ljmerza** [comment]
This could be the issue. I noticed if I had over 200 emails then everything would time out
