### ISSUE TITLE
Tracking daily Georgia Power usage summary

### ISSUE THREAD

**Issue by arsaboo** [ljmerza/ha-email-sensor#17]
My utility company provides a daily usage summary via email (see screenshot attached). I was wondering if we can extract the energy usage and the cost from that email. While this is not a traditional "tracking" feature, I feel like it will be a great feature to add that can potentially be extended to other features. 

![image](https://user-images.githubusercontent.com/18319734/69167819-8e44de80-0ac3-11ea-8ea8-d5403774ea68.png)

**Comment by ljmerza** [comment]
I would need a copy of the original email to add this in ljmerza@gmail.com

Also, there's no frontend card to support this so someone would have to create it (but it will be a sensor attr so it can be used in automation)

**Comment by arsaboo** [comment]
@ljmerza I just emailed you the same. Thanks!

**Comment by ljmerza** [comment]
hey i just added this in v2.3.1. If you hve more than one email it might return an array of objects for each Georgia Power email found

```
 "georgia_power": [
    {
      "yesterday_use": "21 kWh",
      "yesterday_cost": "$3",
      "monthly_use": "516 kWh",
      "monthly_cost": "$66"
    }
  ]
```
