### ISSUE TITLE
custom imap server

### ISSUE THREAD

**Issue by Prostetnic-Jeltz** [ljmerza/ha-email-sensor#18]
Installed Version via HACS: 2.2.0

When trying to create a new sensor with custom imap server and imap port, home assistant produces following error:
> Configuration invalid
> Invalid config for [sensor.email]: [imap_server] is an invalid option for [sensor.email]. Check: sensor.email->imap_server. (See ?, line ?). 

maybe because of the constants in
ha-email-sensor/custom_components/email/const.py
> CONF_IMAP_SERVER = 'smtp_server'
> CONF_IMAP_PORT = 'smpt_port'

changing imap to smtp or smpt seems to help

**Comment by ljmerza** [comment]
yes, i missed that part when updating the config. changed in v2.2.1 thanks!
