### ISSUE TITLE
imap_server not work!

### ISSUE THREAD

**Issue by Kraineff** [ljmerza/ha-email-sensor#19]
Error in log: `Invalid config for [sensor.email]: [imap_server] is an invalid option for [sensor.email]. Check: sensor.email->imap_server. (See ?, line ?). `

Sensor:
```
- platform: email
   email: my_email@yandex.ru
   password: my_password
   imap_server: imap.yandex.ru
   imap_port: 993
```

**Comment by KyleStilkey** [comment]
Yes, it seems that with the latest version the command got reverted back to smtp.

If you want to fix this, just edit the const.py file and update the commands 

CONF_IMAP_SERVER = 'smtp_server'
CONF_IMAP_PORT = 'smtp_port'
to
CONF_IMAP_SERVER = 'imap_server'
CONF_IMAP_PORT = 'imap_port'

[const.zip](https://github.com/ljmerza/ha-email-sensor/files/4284785/const.zip)

I also uploaded the file if you want to replace it yourself. The file is located under config\custom_components\email\

**Comment by ljmerza** [comment]
Fixed
