### ISSUE TITLE
[Feature Request] Add DHL tracking number

### ISSUE THREAD

**Issue by ljmerza** [ljmerza/ha-email-sensor#2]
I don't have an example email for this but if anyone is willing to donate I promise to only use it for science! ljmerza@gmail.com

**Comment by Styx85** [comment]
email sent

**Comment by ljmerza** [comment]
added to v1.5.0 let me know if it works!

**Comment by Styx85** [comment]
would love to test it, but I still havent figured out how to get the email sensor running on my hassio raspi environment. guess there are some dependencies missing and i dont know how to install them manually without pip access
