### ISSUE TITLE
Support for Amazon & Card Suggestions

### ISSUE THREAD

**Issue by KyleStilkey** [ljmerza/ha-email-sensor#20]
I would love to see support added for Amazon added to this, I know there is one already that this is based off from, but it's very outdated and doesn't work half the time, plus setting it up is a royal pain.

I would love to see a update to the card, not sure how customizable it can be but maybe have a way to show est delivery dates and status of the package (out for delivery, on hold so forth).

Another request I would like to see is if there is multiple detections of the same tracking number, it should ignore extras. Currently I have USPS, UPS and FedEx email me whenever there is a package being sent my way and sometimes you can get multiple email updates from shipping making the card show about 3-5 of the same tracking number.

**Comment by ljmerza** [comment]
Amazon doesn't make this easy and it wouldn't be worth the hassle to keep this working. The issue with removing duplicates is automatically knowing which duplicate to get rid of. I'll look into this one but will create a separate issue for it for me to keep track of it.
