### ISSUE TITLE
Option to ignore SSL checking

### ISSUE THREAD

**Issue by Unthred** [ljmerza/ha-email-sensor#25]
I have an old synology NAS and use its mailplus server. My pfsense firewall is responsible for renewing my domains wildcard LetsEncrypt certs.
The certs pass in SSL Checker with the warning 
The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.

**Describe the solution you'd like**
Would it be possible to have a flag to ignore SSL cert errors? As this is all in house I am not worried about SSL

Thanks

**Comment by ljmerza** [comment]
add `ssl` option in `2.13.0`

**Comment by Unthred** [comment]
Amazing what a speedy response!
