### ISSUE TITLE
Home Depot Issue

### ISSUE THREAD

**Issue by gdreelin** [ljmerza/ha-email-sensor#27]
I updated the integration in HACS but upon reboot I get an error that it cannot find "Home Depot" component. I deleted it all and reinstalled it. I got the same thing. I tried pulling all the custom_components files down to override them and still same issue. The fix was to delete the two lines that contain "Home Depot" and the sensor works again. 

I just figured I would give you heads up on that.

**Comment by brendanm720** [comment]
I am also having the same issue. 

The same fix also worked for me.  (Thanks for the tip @gdreelin)

**Comment by guevara777** [comment]
Thank you. That solved my Problem!!!

**Comment by ljmerza** [comment]
Fixed
