### ISSUE TITLE
Latest homeassistant needs imapclient==2.2.0

### ISSUE THREAD

**Issue by jdeath** [ljmerza/ha-email-sensor#32]
Was getting lots of errors due to IMAP client being passed the wrong number of arguments. Something changed in core-2021.7.X.
Changing entry in manifest to "imapclient==2.2.0" fixed the problem

**Comment by kovaccs** [comment]
This is a good workaround, thank you!

**Comment by drjeseuss** [comment]
I also had this issue after updating core.  For those not sure of process, make the edit noted above to custom_components/email/manifest.json then restart core to apply.

**Comment by ljmerza** [comment]
Fixed
