### ISSUE TITLE
Platform error sensor.email

### ISSUE THREAD

**Issue by KyleStilkey** [ljmerza/ha-email-sensor#46]
I've not used this in awhile and saw there was a update so I wanted to give it a try again and I put this in my configuration.yaml file

sensor:
  - platform: email
    email: (email)
    password: (password)

When attempting to check the results come back as
Platform error sensor.email - Exception importing custom_components.email.sensor

I'm not sure if I set something up or there is an issue. Appreciate any help! Thanks!

**Comment by Selim042** [comment]
I got the same thing, I think it is from this commit, line 313 is inconsistent with tabs and spaces.
https://github.com/ljmerza/ha-email-sensor/commit/b6b6f153408d84c4a10c349c052d12ccb0171d47

**Comment by tiduspup** [comment]
Hello

i confirm, replacing "tab" with "space" to align the block correctly fix the issue.

<img width="667" alt="Screenshot 2022-12-07 at 23 46 03" src="https://user-images.githubusercontent.com/23476260/206313843-47512272-d4f2-4fc1-84df-01779cfc1aab.png">
<img width="614" alt="Screenshot 2022-12-07 at 23 43 17" src="https://user-images.githubusercontent.com/23476260/206313846-dafc2bf7-7504-4d0c-9268-929db633b262.png">
