### ISSUE TITLE
HA won't start when I add email sensor to my config

### ISSUE THREAD

**Issue by seaverd** [ljmerza/ha-email-sensor#8]
Would love some assistance.  I am attempting to add this email sensor to my Home Assistant running in docker, current version 0.92.2

I have followed the instructions, unzipped the file to the correct location, performed the PIP install for the items listed in the instructions and created a google app password and added the required settings to the sensor section of the configuration.yaml

When I check the configuration I get Configuration is Valid however when I restart home assistant, it never loads the webgui.   I checked logs and it stops right after logger is started (generally this is where the components load).   If I comment out the email sensor and then restart the webgui loads.  

Any suggestions on how to troubleshoot this?

Thanks,
Dan

**Comment by ljmerza** [comment]
try adding debug level to the loader and core

**Comment by allanpersson** [comment]
@seaverd did you remember to add the integration to your HA configuration file? In my case i had to use the following in my sensor data for my account to allow access:
platform: email
email: 'my@email.dk'
password: 'my_password'
smtp_server: myimap.one.com

Hope it will work out for you :D

**Comment by seaverd** [comment]
Haven't played with this in a while.  I now have HACs setup so I installed
email sensor via that.  Below is my configuration:

  - platform: email
    email: myemail@gmail.com
    password: mytoken
    smtp_server: imap.gmail.com
    smtp_port: 993

Here is the error I get in my logs:
2019-07-23 21:01:22 ERROR (MainThread) [homeassistant.config] Invalid
config for [sensor.email]: [smtp_port] is an invalid option for
[sensor.email]. Check: sensor.email->smtp_port. (See
/config/configuration.yaml, line 71). Please check the docs at
https://home-assistant.io/components/sensor.email/

Dan

**Comment by ljmerza** [comment]
you dont need the smtp settings for google. try without them

**Comment by seaverd** [comment]
If I comment out smtp_port and smtp_server the HA UI does not load.  The
last 2 entries in my log is:

2019-07-23 22:13:11 INFO (MainThread) [homeassistant.bootstrap] Setting up
{'logger', 'system_log'}
2019-07-23 22:13:11 INFO (MainThread) [homeassistant.setup] Setting up
logger

**Comment by seaverd** [comment]
Added debug level to the loader and core.  I see mailparser working away.
My mailbox is out of control...does it just take a long time?  Will it do
this on every restart?

**Comment by seaverd** [comment]
It looks like it does take awhile...must not have been patient enough before.  I had 5300 unread emails in my promotions tab.  After deleting these HA UI loads like it did before adding this sensor.  So this can be marked as closed.  

All I need to do now to test it is to order something :)

Thanks,
Dan
